### ISSUE TITLE
Rename icons

### ISSUE THREAD

**Issue by Stichoza** [Stichoza/font-larisome#2]
Rename icons all icons (assuming #1 is resolved).

I need feedback from community about icon names.

**Comment by thecotne** [comment]
მოკლე სახელები მგონი ზედმეტია makes no sense
დანარჩენი იყოს რას ერჩი? ფოტოზე ნახავ რაც მოუხდება იმას ჩააგდებ სახელს არ აქვს დიდი მნიშვნელობა

და ეს რა პონტია?
https://github.com/Stichoza/font-larisome/blob/master/src/stylus/_icons.styl#L47
&wtf?

**Comment by Stichoza** [comment]
მოკლე სახელები ანუ `lari-a`, `lari-b` და ა.შ? ეგ უნდა იყოს ზუსტად. ახლა ვინც იყენებს პირდაპირ ფონტებით, ასე აქვთ დაახლოებით: `<span style="font-family:Lari">A</span>` ან უკეთეს შემთხვევაში `<span class="lari">B</span>`. მოკლე სახელები მიგრაციისთვის კარგი იქნება, თან მოხერხებულია.

აქ უბრალოდ იმაზეა საუბარი, რომ არაკონსტრუქციული სახელებია. მაგალითად `lari-square-narrow` და `lari-narrow-serif` – ერთში narrow წინაა და მეორეში უკან. ხოდა php-ის ვარიანტი იქნება s

**Comment by Stichoza** [comment]
wtf-ს რაც შეეხება, ეგ მაგარი რამეა, `lari-wtf` წერს მაგ სიმბოლოს, დებილი სიმბოლოა და მაგპონტში :smile: (alias of `lari-comic`)
