### ISSUE TITLE
preview images outdated

### ISSUE THREAD

**Issue by thecotne** [Stichoza/font-larisome#3]
@Stichoza 
![capture](https://cloud.githubusercontent.com/assets/1606993/7550405/670ef6bc-f672-11e4-853f-0c587a05c6b3.PNG)

**Comment by Stichoza** [comment]
Have no idea about this. Obviously they're not outdated as they're just loaded randomly, i.e. different images are loaded at different requests

**Comment by thecotne** [comment]
```
http://lkjsdflkjsdf.cf/font-larisome/a.png
http://lkjsdflkjsdf.cf/font-larisome/b.png
http://lkjsdflkjsdf.cf/font-larisome/c.png
http://lkjsdflkjsdf.cf/font-larisome/d.png
http://lkjsdflkjsdf.cf/font-larisome/e.png
http://lkjsdflkjsdf.cf/font-larisome/f.png
http://lkjsdflkjsdf.cf/font-larisome/g.png
http://lkjsdflkjsdf.cf/font-larisome/h.png
http://lkjsdflkjsdf.cf/font-larisome/i.png
http://lkjsdflkjsdf.cf/font-larisome/j.png
http://lkjsdflkjsdf.cf/font-larisome/k.png
http://lkjsdflkjsdf.cf/font-larisome/l.png
http://lkjsdflkjsdf.cf/font-larisome/m.png
http://lkjsdflkjsdf.cf/font-larisome/n.png
http://lkjsdflkjsdf.cf/font-larisome/o.png
http://lkjsdflkjsdf.cf/font-larisome/p.png
```

ამათგან არცერთზე არ შედის რასაც ხსნის ეგ github ის რაღაც ქეშია
imgur ზე ატვირთე ან repo ში ეგ ფოტოებიც დაამატე

**Comment by Stichoza** [comment]
Ah, ჰო, ეგ სერვერი სნეფშოთიდან აღვადგინე და დამავიწყდა ეგ. თუ მაქვს შემორჩენილი ეგ იმიჯები ვიზამ ცოტა მერე :დ

**Comment by thecotne** [comment]
ფოტოები
![a](https://cloud.githubusercontent.com/assets/1606993/7555191/57938f8a-f754-11e4-9792-7a0f961e83fb.png)
![b](https://cloud.githubusercontent.com/assets/1606993/7555192/57941630-f754-11e4-8123-6ff7f467b411.png)
![c](https://cloud.githubusercontent.com/assets/1606993/7555194/579ab1a2-f754-11e4-9f02-0d2887cd9af1.png)
![d](https://cloud.githubusercontent.com/assets/1606993/7555195/579d2068-f754-11e4-8ab4-6edb2a22e225.png)
![e](https://cloud.githubusercontent.com/assets/1606993/7555181/574a0d7e-f754-11e4-9fc8-230bb619183b.png)
![f](https://cloud.githubusercontent.com/assets/1606993/7555182/574d6dca-f754-11e4-86f9-45a08f5227e5.png)
![g](https://cloud.githubusercontent.com/assets/1606993/7555183/576678c4-f754-11e4-8563-e16da95c259a.png)
![h](https://cloud.githubusercontent.com/assets/1606993/7555184/57671cd4-f754-11e4-83bb-8d59473c9aae.png)
![i](https://cloud.githubusercontent.com/assets/1606993/7555187/577a5308-f754-11e4-97a2-a78ed434defa.png)
![j](https://cloud.githubusercontent.com/assets/1606993/7555186/5779d414-f754-11e4-9b31-b9af9bdb3d7d.png)
![k](https://cloud.githubusercontent.com/assets/1606993/7555185/57799b8e-f754-11e4-93ca-50223ecc8681.png)
![l](https://cloud.githubusercontent.com/assets/1606993/7555214/df000d22-f754-11e4-814d-52dc4640444e.png)
![m](https://cloud.githubusercontent.com/assets/1606993/7555188/577e4332-f754-11e4-9358-fcbae1263550.png)
![n](https://cloud.githubusercontent.com/assets/1606993/7555190/5783a548-f754-11e4-84d6-806d56279c6b.png)
![o](https://cloud.githubusercontent.com/assets/1606993/7555189/5781b6c0-f754-11e4-97ba-a3caa435fb19.png)
![p](https://cloud.githubusercontent.com/assets/1606993/7555193/5795b01c-f754-11e4-9948-4c977fcb89bc.png)
