### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by vdanelia** [Stichoza/font-larisome#5]
გაიხარე ძლივს არ ვნახე ლარის სიმბოლო..... Font-Awesome - ზეც ვნახე შენი მოთხოვნა :) მეც მივამატე პლუსი იმედია მანდაც დაემატება 

:+1:

**Comment by Stichoza** [comment]
გამზადებული ფონტები დავულინკე ყველა ფორმატში და დანარჩენს იზამენ ალბათ :smile:
